import Head from "next/head";
import styled from "styled-components";
import NavbarUser from "../../components/NavbarUser"

const EndSessionStyle = styled.div `
text-align: center;
padding: 0 20px;
button {
    background-color: var(--yellow);
    border: 1px solid var(--yellow);
    padding: 15px 30px;
    margin-top: 30px;
    font-family: 'Helvetica';
    border-radius: 5px;
    cursor: pointer;
    
    &:hover{
        background-color: var(--white);
        border: 1px solid var(--black);
    }
}
`

export default function EndSession() { 
    return(
        <>
            <Head>
            <title>Fin de session</title> 
            <meta name = "description" content = "Generated by create next app" />
            <meta name = "viewport" content = "width=device-width, initial-scale=1" />
            <link rel = "icon" href = "/favicon.ico" />
            </Head>

            <EndSessionStyle>

            <NavbarUser />

            <p>Merci d'avoir participé</p>
            <p>À bientôt</p>

            <button>Quitter la session</button>
            </EndSessionStyle>
        </>

    )
}