import Head from "next/head";
import styled from "styled-components"
import NavbarUser from "../../components/NavbarUser"
import Link from "next/link";
import { getCookie } from 'cookies-next';
import { useEffect,useState } from 'react';

const IndexStyle = styled.div`
.session{
    height: 60vh;
    display: flex;
    align-items: center;
    flex-direction: column;
    justify-content: center;
}
button {
    background-color: var(--yellow);
    border: 1px solid var(--yellow);
    padding: 15px 35px;
    font-family: 'Helvetica';
    text-align: center;
    border-radius: 5px;
    display: block;
    margin: 20px auto;
    cursor: pointer;
    &:hover{
        background-color: var(--white);
        border: 1px solid var(--black);
    }

}
`



export default function Index(){
    const [Datas,setDatas] = useState([])
    const fetchData = async () => {
        const res = await fetch('/api/session/pre_session',{
            method: 'POST',
            headers: {
                'Content-Type': 'application/json'
            },body: JSON.stringify({id_session:getCookie('id_session')}
            )
        })
        const data_get = await res.json()
        setDatas(data_get)
    }

    useEffect(()=>{
        fetchData()
    },[])

    

    return(
        <>
        <IndexStyle>
        <Head>
        <title>ColorVote</title> 
        <meta name = "description" content = "Generated by create next app" />
        <meta name = "viewport" content = "width=device-width, initial-scale=1" />
        <link rel = "icon" href = "/favicon.ico" />
        </Head>
        <NavbarUser />
        <div className="session">
    
        <h1>{Datas.name} </h1>

        <p>{Datas.nb_page} questions</p>
        <p>À chaque question, sélectionner une réponse.</p>
        
        <Link href="user/questionsSession">
            <button >Commencer</button>

        </Link>
        </div>
        </IndexStyle>
        </>
    )
}