import Head from 'next/head'
import styled from 'styled-components'
import Image from 'next/image'

const HomeStyle = styled.div`

height: 100vh;
text-align: center;
font-family: 'Helvetica';
padding: 20px;

.button__section{
  margin-top: 50px;
  .admin__button, .user__button{
    background-color: var(--white);
    border: 1px solid var(--black);
    padding: 15px 20px;
    width: 180px;
    border-radius: 8px;
    cursor: pointer;

    &:hover{
      background-color: var(--black);
      color: var(--white);
    }
  }


  .admin__button{
    margin-right: 10px;
  }

  .user__button{
    margin-left: 10px;
  }
}

form{
margin-top: 50px;
display: flex;
flex-direction: column;
align-items: center;
gap: 20px;
  input{
    width: 550px;
    border-radius: 8px;
    padding: 15px 20px;
    border: 1px solid var(--black);
  }

  button[type='submit'] {
    background-color: var(--yellow);
    border: 1px solid var(--yellow);
    padding: 15px 30px;
    margin-top: 30px;
    font-family: 'Helvetica';
    border-radius: 5px;
    cursor: pointer;

    &:hover{
      background-color: var(--white);
      border: 1px solid var(--black);
    }
  }
}
@media(max-width: 768px){
  input{
    width: 100%!important;

  }
  .admin__button, .user__button{
    width: 130px!important;
  }
}

` 
export default function Home() {
  
  return (
    <>
    <HomeStyle>
      <Head>
       
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>
        <Image src="/img/ColorVote.png"
        width={180}
        height={150}
        /></h1>
        <h2>Vous êtes ?</h2>

        <div className='button__section'>
          <button className='admin__button'>Admin</button>
          <button className='user__button'>Utilisateur</button>
        </div>

          <form
          action="POST"
          >
            <input
            type="text"
            id="username" 
            name='username' 
            placeholder='Nom utilisateur'
            required
            />

            <input 
            type="text" 
            id='pinNumber' 
            name='pinNumber' 
            placeholder='Code PIN'
            required
            />

            <button type='submit' className='login__button'>Se connecter</button>
          </form>

      </HomeStyle>
    </>
  )
}
