import styled from "styled-components"
import Head from "next/head"

const FormStyle = styled.div `
h1{
    text-align: center;
}

form{
    margin: 20px;
    text-align: center;
    input{
        width: 100%;
        padding: 15px 20px;
    }

}

button[type='submit'] {
    background-color: var(--yellow);
    border: 1px solid var(--yellow);
    padding: 15px 35px;
    margin-top: 30px;

  }
`
export default function form() {
    return ( 
        <>
        <FormStyle >
        <Head>
        <title>ColorVote</title> 
        <meta name = "description" content = "Generated by create next app" />
        <meta name = "viewport" content = "width=device-width, initial-scale=1" />
        <link rel = "icon" href = "/favicon.ico" />
        </Head> 
        <h1> Créer un questionnaire </h1>

        <form action = "POST" >
        <input type = "text"
        placeholder = "Le sport a-t-il des bienfaits sur la santé ?" />

        <button type="submit">Ajouter</button>
        </form> 

        <h2>Les questions :</h2>

        <button type="submit">Suivant</button>
        </FormStyle> 
        </>
    )
}