import styled from "styled-components";
import Head from "next/head";
import Chart from 'chart.js/auto';
import Navbar from "../../components/Navbar";
import PieCharts from "../../components/PieCharts";

const StatisticStyle = styled.div`
padding: 0 20px;
width: 80vw;
margin-left: 20vw;
font-family: "Helvetica";
h1{
    text-align: center;
}

p{
    margin: 0;
}
.information{
    text-align: end;
}

.graphic{
    display: flex;
    justify-content: space-around;
    margin-top: 50px;

.legend{
li{
    list-style-type: none;
    margin-top: 10px;
    display: flex;
}
.color{
    height: 20px;
    width: 20px;
    margin-right: 10px;
    
}

.answers{
    display: flex;
}
.piecharts{
    width: 200px;
}
`

export default function Statistic() {
    return (

        <>
    <StatisticStyle>
        <Head>
        <title>Les statistiques</title> 
        <meta name = "description" content = "Generated by create next app" />
        <meta name = "viewport" content = "width=device-width, initial-scale=1" />
        <link rel = "icon" href = "/favicon.ico" />
        </Head>
        <Navbar />
        <h1>Les statistiques</h1>

        <p>Imprimer</p>
        <div className="information">
            <p>Session : </p>
            <p>Nombre de questions : </p>
            <p>Nombre de participants : </p>
        </div>

        <section className="graphic">
            <div className="piecharts">
            <PieCharts />
            </div>

            
        </section>
    </StatisticStyle>
        </>
    )
}