import styled from "styled-components";
import Head from "next/head";
import Chart from 'chart.js/auto';

const StatisticStyle = styled.div`
padding: 0 20px;
h1{
    text-align: center;
}

p{
    margin: 0;
}
.information{
    text-align: end;
}

.graphic{
    display: flex;
    justify-content: space-around;
    margin-top: 50px;
.legend{
li{
    list-style-type: none;
    margin-top: 10px;
    display: flex;
}
.color{
    height: 20px;
    width: 20px;
    margin-right: 10px;
    
}


.darkgreen{
    background-color: var(--darkgreen);
}

.lightgreen{
    background-color: var(--lightgreen);
}

.orange{
    background-color: var(--orange);
}
.lightred{
    background-color: var(--lightred);
}

.darkred{
    background-color: var(--darkred);
}

.white{
    background-color: var(--white);
    border: 1px solid var(--black);
}

.black{
    background-color: var(--black);
}
}
}

.answers{
    display: flex;

}

`
export default function Statistic() {
    return (

        <>
    <StatisticStyle>
        <Head>
        <title>Les statistiques</title> 
        <meta name = "description" content = "Generated by create next app" />
        <meta name = "viewport" content = "width=device-width, initial-scale=1" />
        <link rel = "icon" href = "/favicon.ico" />
        </Head>

        <h1>Les statistiques</h1>

        <p>Imprimer</p>
        <div className="information">
            <p>Session : </p>
            <p>Nombre de questions : </p>
            <p>Nombre de participants : </p>
        </div>

        <section className="graphic">
            <div>Graphique</div>
            <div className="legend">
                <p>Légende :</p>
                    <ul>
                        <li><div className="darkgreen color"></div>Tout à fait d'accord</li>
                        <li><div className="lightgreen color"></div>D'accord</li>
                        <li><div className="orange color"></div>Mitigé</li>
                        <li><div className="darkred color"></div>Pas d'accord</li>
                        <li><div className="lightred color"></div>Pas du tout d'accord</li>
                        <li><div className="white color"></div>Aucun Avis</li>
                        <li><div className="black color"></div>Pas de réponse</li>
                    </ul>
            </div>
        </section>
        <hr />
        <div className="answers">
            <ul>
                <li>Le sport a-t-il des bienfaits ?  
                <div className="darkgreen color"></div>
                </li>
                <li>
                    La chasse est-il un sport ?
                </li>
                <li>Penses-tu que le sport est un moyen de s'épanouir ?</li>
            </ul>
        </div>
    </StatisticStyle>
        </>
    )
}