import styled from "styled-components"
import Head from "next/head"
import Navbar from "../../components/Navbar"

const StyleSummaryQuestions = styled.div `
text-align: center;
width: 80vw;
margin-left: 20vw;

button[type=submit]{
    background-color: var(--yellow);
    border: 1px solid var(--yellow);
    padding: 15px 30px;
    margin-top: 30px;
    font-family: 'Helvetica';
    border-radius: 5px;
    cursor: pointer;
    
    &:hover{
        background-color: var(--white);
        border: 1px solid var(--black);
    }
}
`
export default function SummaryQuestions() {
    return ( 
    <>
    <StyleSummaryQuestions>
    <Head>
        <title>Bilan des questions</title> 
        <meta name = "description" content = "Generated by create next app" />
        <meta name = "viewport" content = "width=device-width, initial-scale=1" />
        <link rel = "icon" href = "/favicon.ico" />
        </Head>
        <Navbar />
        <h1>Bilan des Questions</h1> 
        <div> </div> 
        <button type = "submit">Lancer la session</button> 
        </StyleSummaryQuestions> </>
    )
}