import styled from 'styled-components'
import Navbar from '../../components/Navbar'
import Head from 'next/head';
import User from '../../components/user';
import { useEffect,useState } from 'react';

const UsersStyle = styled.div`
width: 80vw;
margin-left: 20vw;
font-family: "Helvetica";
padding: 20px;

h1{
    text-align: center;
}

form{
    margin: 20px 0px;
    
    input{
        padding: 10px 20px;
        margin-right: 10px;
    }
    button[type='submit'] {
        background-color: var(--yellow);
        border: 1px solid var(--yellow);
        padding: 15px 30px;
        margin-top: 30px;
        font-family: 'Helvetica';
        border-radius: 5px;
        cursor: pointer;

    &:hover{
            background-color: var(--white);
            border: 1px solid var(--black);
    }
    }
}
table {
        width: 100%;
}

thead{
    background-color: #f5b60d;

}
th {
    letter-spacing: 2px;
    padding: 10px;
    text-align: start;
}

td{
    padding: 20px 8px;
}
tr{
    padding: 10px;
}
tbody tr:nth-child(even) {
    background-color: #dbdbdb;
}
tbody tr:nth-child(odd) {
    background-color: #f4f4f4;
}
`



export default function Users() {
    const [Datas,setDatas] = useState([])

    const fetchData = async () => {
        const res = await fetch('/api/form/form_user')
        const data_get = await res.json()
        setDatas(data_get)
    }

    useEffect(()=>{
        fetchData()
    },[])


    return(
        <>
        <UsersStyle>
        <Head>
        <title>Liste des utilisateurs</title> 
        <meta name = "description" content = "Generated by create next app" />
        <meta name = "viewport" content = "width=device-width, initial-scale=1" />
        <link rel = "icon" href = "/favicon.ico" />
        </Head>

        <Navbar />
        <h1>Liste des utilisateurs</h1>
        <form onsubmit="handleSubmitPost" method="POST">
            <input type="text" name='name' id='name' placeholder='Nom' />

            <input type="text" name='firstname' id='fistname' placeholder='Prénom' />

            <input type="text" name='email' id='email' placeholder='Email' />

            <select name="choix des acitivités">
                <option value="">-- activité--</option>
                {
                    
                    Datas.activity?.map((activity)=>{
                        <option value={activity.activityName}>{activity.activityName}</option>

                    })
                }
            </select>

            <select name="choix des groups">
                <option value="">-- groupe--</option>
                {   
                    Datas.group?.map((group)=>{
                        <option value={group.groupName}>{group.groupName}</option>

                    })
                }
            </select>




            <button type='submit'>Ajouter</button>
        </form>
            <table>
                <thead>
                    <tr>
                        <th>Nom</th>
                        <th>Prénom</th>
                        <th>Email</th>
                        <th>Activité</th>
                        <th>Groupe</th>
                    </tr>
                </thead>
                <tbody>
                </tbody>
            </table>
            </UsersStyle>
        </> 
        
    )
}