import styled from 'styled-components'
import Navbar from '../../components/Navbar'
import Head from 'next/head';

const UsersStyle = styled.div`
width: 80vw;
margin-left: 20vw;
font-family: "Helvetica";
padding: 20px;

h1{
    text-align: center;
}

table {
        width: 100%;
}

thead{
    background-color: #f5b60d;

}
th {
    letter-spacing: 2px;
    padding: 10px;
    text-align: start;
}

td{
    padding: 20px 8px;
}
tr{
    padding: 10px;
}
tbody tr:nth-child(even) {
    background-color: #dbdbdb;
}
tbody tr:nth-child(odd) {
    background-color: #f4f4f4;
}
`
export default function Users() {
    return(
        <>
        <UsersStyle>
        <Head>
        <title>Liste des utilisateurs</title> 
        <meta name = "description" content = "Generated by create next app" />
        <meta name = "viewport" content = "width=device-width, initial-scale=1" />
        <link rel = "icon" href = "/favicon.ico" />
        </Head>

        <Navbar />
        <h1>Liste des utilisateurs</h1>
            <table>
                <thead>
                    <tr>
                        <th>Nom</th>
                        <th>Prénom</th>
                        <th>Email</th>
                        <th>Activité</th>
                        <th>Groupe</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td>Kouao</td>
                        <td>Jefferson</td>
                        <td>kouaojeff@gmail.com</td>
                        <td></td>
                        <td></td>
                    </tr>
                    <tr>
                        <td>Kouao</td>
                        <td>Jefferson</td>
                        <td>kouaojeff@gmail.com</td>
                        <td></td>
                        <td></td>
                    </tr>
                </tbody>
            </table>
        </UsersStyle>
        </> 
        
    )
}